version: '3.6'

networks:
  elk:
    driver: bridge

services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_BUCKET=ChangeDetection
      - INFLUXDB_ORG=ChangeDetection_org

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
 
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
      

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"

  kafka_data_stream_conversion:
    build:
      context: ./data_stream
      dockerfile: Dockerfile
    volumes:
      - ./data_stream:/app  
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
    #command: ["python", "/data_stream/kafka_data_stream_conversion.py"]

  model_training:
    build:
      context: ./model
      dockerfile: Dockerfile
    volumes:
      - ./model:/app  
    depends_on:
      - influxdb  
    environment:
      - INFLUXDB_URL=http://influxdb:8086  
      - INFLUXDB_TOKEN=ZBOYRf26zzXnAwWMht0_ysJHoadZFwTTsVSaOrbl1bQgnjx2OchxIHsK5qnQUvUczTRcGWbdA1SacnhQEKrZog==  # InfluxDB token
      - INFLUXDB_ORG=ChangeDetection_org
      - INFLUXDB_BUCKET=ChangeDetection
    #command: ["python", "/model/model_training.py"]

  saving_influxdb: 
    build:
      context: ./influxdb_save
      dockerfile: Dockerfile
    depends_on:
      - kafka  
      - influxdb  
    environment:
      - KAFKA_SERVER=kafka:9092
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=ZBOYRf26zzXnAwWMht0_ysJHoadZFwTTsVSaOrbl1bQgnjx2OchxIHsK5qnQUvUczTRcGWbdA1SacnhQEKrZog==
      - INFLUXDB_ORG=ChangeDetection_org
      - INFLUXDB_BUCKET=ChangeDetection
    volumes:
      - ./influxdb_save:/app  
    #command: ["python", "/influxdb_save/saving_InfluxDB.py"]


volumes:
  influxdb-data:
  zookeeper-data:
    driver: local
  kafka-data:
    driver: local
