FROM python:3.9.6

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY kafka_Spark_intergration.py /app/

CMD ["python", "kafka_Spark_intergration.py"]  