{
 "title": "Pipeline4_Evaluation of PageHinkley",
 "time": { "from": "2024-12-07T11:33:41.012Z", "to": "2024-12-07T11:48:37.299Z" },
 "panels": [
  {
   "title": "Distribution of DstJitter column",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ChangeDetection\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PageHinkleyResults\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"DstJitter\"])"
    }
   ]
  },
  {
   "title": "Precision, Recall, F1 score and Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ChangeDetection\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PageHinkleyResults\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({r with prec: if r.TP + r.FP != 0 then (r.TP / (r.TP + r.FP)) else 0 }))\n  |> map(fn: (r) => ({r with recall: if r.TP + r.FP != 0 then (r.TP / (r.TP + r.FN)) else 0 }))\n  |> map(fn: (r) => ({ r with f1_score: if (r.prec + r.recall) != 0 then (2 * r.prec * r.recall / (r.prec + r.recall)) else 0 }))\n  |> map(fn: (r) => ({ r with accuracy: if (r.TP + r.TN + r.FP + r.FN) != 0 then ((r.TP + r.TN) / (r.TP + r.TN + r.FP + r.FN)) else 0 }))\n  |> keep(columns: [\"_time\", \"prec\", \"recall\", \"f1_score\", \"accuracy\"])\n"
    }
   ]
  },
  {
   "title": "Aggregated precision, recall, f1_score and accuracy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ChangeDetection\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PageHinkleyResults\")\n  |> drop(columns: [\"result\"])\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({r with prec: if (r.TP + r.FP) != 0.0 then (r.TP / (r.TP + r.FP)) else 0.0 }))\n  |> map(fn: (r) => ({r with recall: if r.TP + r.FP != 0.0 then (r.TP / (r.TP + r.FN)) else 0.0 }))\n  |> map(fn: (r) => ({ r with f1_score: if (r.prec + r.recall) != 0.0 then (2.0 * r.prec * r.recall / (r.prec + r.recall)) else 0.0 }))\n  |> map(fn: (r) => ({ r with accuracy: if (r.TP + r.TN + r.FP + r.FN) != 0.0 then ((r.TP + r.TN) / (r.TP + r.TN + r.FP + r.FN)) else 0.0 }))\n  |> keep(columns: [\"prec\", \"recall\", \"f1_score\", \"accuracy\"])"
    }
   ]
  }
 ]
}