{
 "title": "New dashboard",
 "time": { "from": "2024-12-06T23:44:15.000Z", "to": "2024-12-07T00:32:21.000Z" },
 "panels": [
  {
   "title": "Lightweight Process",
   "type": "gauge",
   "description": "Used to monitor the concurrency of the program. If the number of Goroutines continues to grow, it may mean that some Goroutines are not properly recycled, resulting in resource leaks.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ChangeDetection\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"go_goroutines\" and\r\n    r._field == \"gauge\"\r\n  )"
    }
   ]
  },
  {
   "title": "Current heap memory usage",
   "type": "gauge",
   "description": "The unit is bytes. The server has 4GB of memory. More than 3GB may be a warning sign.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ChangeDetection\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"go_memstats_heap_inuse_bytes\" and\r\n    r._field == \"gauge\"\r\n  )"
    }
   ]
  },
  {
   "title": "Duration of garbage collection operations",
   "type": "histogram",
   "description": "这个指标表示每次垃圾回收操作所花费的时间，单位是秒。",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"ChangeDetection\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"go_gc_duration_seconds\" and\r\n    r._field == \"count\"\r\n  )"
    }
   ]
  },
  {
   "title": "Database read load",
   "type": "timeseries",
   "description": "Total number of database read and write operations.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"ChangeDetection\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"boltdb_reads_total\" and\r\n    r._field == \"counter\" or\r\n    r._measurement == \"boltdb_writes_total\" and\r\n    r._field == \"counter\" \r\n  )"
    }
   ]
  },
  {
   "title": "Memory allocation",
   "type": "stat",
   "description": "This metric indicates the total amount of memory allocated since the program was started, in bytes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ChangeDetection\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"go_memstats_alloc_bytes_total\" and\r\n    r._field == \"counter\"\r\n  )"
    }
   ]
  }
 ]
}