{
 "title": "Over time trend",
 "time": { "from": "2024-12-02T11:13:31.000Z", "to": "2024-12-02T23:17:27.000Z" },
 "panels": [
  {
   "title": "Total Packets Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ChangeDetection\")\r\n  |> range(start: time(v: 2024-12-02T00:00:00Z), stop: time(v: 2024-12-03T00:00:00Z))  // Specify the time range\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TotPkts\")  // Filter for total packets (TotPkts)\r\n  |> aggregateWindow(every: 1h, fn: sum)  // Aggregate by hour, summing total packets per hour\r\n  |> yield(name: \"Total Packets Aggregated by Hour\")  // Output the result with a name"
    }
   ]
  },
  {
   "title": "Total Bytes Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ChangeDetection\")\r\n  |> range(start: time(v: 2024-12-02T00:00:00Z), stop: time(v: 2024-12-03T00:00:00Z))  // Specify the time range\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TotBytes\")  // Filter for total bytes (TBytes)\r\n  |> aggregateWindow(every: 1m, fn: sum)  // Aggregate by day, summing total bytes per day\r\n  |> yield(name: \"Total Bytes Over Time\")  // Output the result with a name"
    }
   ]
  },
  {
   "title": "Packet Loss Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"ChangeDetection\")\r\n  |> range(start: time(v: 2024-12-02T00:00:00Z), stop: time(v: 2024-12-03T00:00:00Z))  // Time range\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Loss\")  // Filter both \"TotPkts\" and \"Ploss\" fields\r\n  |> aggregateWindow(every: 1m, fn: sum)  // Aggregate both fields every 1 minute\r\n  |> yield(name: \"Total Packet Loss Over Time\")"
    }
   ]
  },
  {
   "title": "Total Load Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"ChangeDetection\")\r\n  |> range(start: time(v: 2024-12-02T00:00:00Z), stop: time(v: 2024-12-03T00:00:00Z))  // Specify the time range\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Load\")  // Filter for total load (Load)\r\n  |> aggregateWindow(every: 1m, fn: sum)  // Aggregate by hour, summing total load per hour\r\n  |> yield(name: \"Total Load Over Time\")  // Output the result with a name"
    }
   ]
  }
 ]
}