{
 "title": "Raw Streaming Data Dashboard",
 "description": "This dashboards shows a few visualisations that explore the raw data streaming in the system",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Top 15 Features by Importance in the last 15 minutes",
   "type": "timeseries",
   "description": "Visualising the top 15 features identified in out EDA",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ChangeDetection\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Traffic\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"DstJitter\", \"TcpRtt\", \"DIntPkt\", \"DstPkts\", \"DstBytes\", \"SynAck\", \"DstRate\", \"DstLoad\", \"sTtl\", \"DstLoss\", \"SAppBytes\", \"pLoss\", \"Sport\", \"dTtl\", \"Dport\"])\n"
    }
   ]
  },
  {
   "title": "Distribution of source IP address frequencies",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ChangeDetection\")\n  |> range(start: -15m) // Adjust the time range as needed\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Traffic\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"SrcAddr\"])\n"
    }
   ]
  },
  {
   "title": "Data in the last 15 minutes",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"ChangeDetection\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Traffic\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"SrcAddr\", \"DstAddr\", \"Sport\", \"Dport\"])\n"
    }
   ]
  },
  {
   "title": "Distribution of source IP address frequencies",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ChangeDetection\")\n  |> range(start: -15m) // Adjust the time range as needed\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Traffic\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"DstAddr\"])\n"
    }
   ]
  }
 ]
}